interactions:
- request:
    body: '{"biller_id": 6900, "account_number": "1111362009"}'
    headers:
      Accept: [application/vnd.regalii.v3.1+json]
      Accept-Encoding: ['gzip, deflate']
      Authorization: ['APIAuth 88879c1b066dc9aea6201f27be2bbba9:uZBixSre2hYYIvGwaLwRF3l2C/o=']
      Connection: [keep-alive]
      Content-Length: ['51']
      Content-MD5: [bQK9pnQdJW/eFR0gpmVoHA==]
      Content-Type: [application/json]
      Date: ['Wed, 12 Dec 2018 18:59:59 GMT']
      User-Agent: [python-requests/2.20.1]
    method: POST
    uri: https://api.casiregalii.com/bills
  response:
    body: {string: '{"code":"R9","message":"Unexpected error (everything entered was
        correct)","id":8391}'}
    headers:
      Cache-Control: [no-cache]
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      Date: ['Wed, 12 Dec 2018 19:00:00 GMT']
      Strict-Transport-Security: [max-age=31536000]
      Transfer-Encoding: [chunked]
      X-Content-Type-Options: [nosniff]
      X-Frame-Options: [SAMEORIGIN]
      X-Request-Id: [067e1b4c-e194-405f-bf3e-5802ce33327c]
      X-Runtime: ['1.051548']
      X-XSS-Protection: [1; mode=block]
    status: {code: 422, message: Unprocessable Entity}
version: 1
