interactions:
- request:
    body: '{"biller_id": 40, "account_number": "501000000004"}'
    headers:
      Accept: [application/vnd.regalii.v3.1+json]
      Accept-Encoding: ['gzip, deflate']
      Authorization: ['APIAuth 88879c1b066dc9aea6201f27be2bbba9:HkH2rfDrZMe5LBN5+t9B5s3n8q8=']
      Connection: [keep-alive]
      Content-Length: ['51']
      Content-MD5: [mDRNhwgEiKn41ooFxmHjFQ==]
      Content-Type: [application/json]
      Date: ['Thu, 17 Jan 2019 17:33:35 GMT']
      User-Agent: [python-requests/2.20.1]
    method: POST
    uri: https://api.casiregalii.com/bills
  response:
    body: {string: '{"code":"R2","message":"Invalid Account Number","id":8389}'}
    headers:
      Cache-Control: [no-cache]
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      Date: ['Thu, 17 Jan 2019 17:33:37 GMT']
      Strict-Transport-Security: [max-age=31536000]
      Transfer-Encoding: [chunked]
      X-Content-Type-Options: [nosniff]
      X-Frame-Options: [SAMEORIGIN]
      X-Request-Id: [52d6fbc8-b85e-4ebd-9180-9ea1ad1725d0]
      X-Runtime: ['1.057218']
      X-XSS-Protection: [1; mode=block]
    status: {code: 422, message: Unprocessable Entity}
version: 1
